comment:
  image:
    repository: z4ph0d/comment
    tag: latest 
  service:
    externalPort: 9292

post:
  image:
    repository: z4ph0d/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: z4ph0d/ui
    tag: "1.0" 
    service: 9292
