global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ruslan_khalimov'
